### ISSUE TITLE
Package request: Fedora/yum

### ISSUE THREAD

**Issue by DominicWatson** [zealdocs/zeal-packaging#1]
I'm running [Korora](https://www.kororaproject.org/), a Fedora based distro, and would love to see a yum based package from which to install.

For now, I've managed to install by building from source:

1. I had to install QT 5.x by using the [QT online installer](https://www.qt.io/download-open-source/) because I couldn't figure out all the diff QT packages (hopefully you're smarter than me)
2. I had to ensure that `/qtinstalllocation/5.4/gcc_64/bin/ ` was in my path (I edited my `~/.bashrc` file to add it to PATH)
3. Cloned the [zeal source repo](https://github.com/zealdocs/zeal)
4. Installed required dependencies for the build: `sudo yum install xcb-util-keysyms-devel libarchive-devel`
5. Ran the build with `qmake` `make` and `sudo make install`

Keep up the great work guys, appreciated :)

**Comment by trollixx** [comment]
I have built Zeal on Fedora 21 with Qt 5 installed from the standard repositories.

There's also a contributed spec file for Fedora in zealdocs/zeal#302:

**Comment by DominicWatson** [comment]
Nice one, thanks trollix - I'll update my comment (got a bit lost with all the diff qt packages)

**Comment by trollixx** [comment]
I am not completely sure whether a spec file fixes this issue, since I am not a user of any RedHat-based distros. Please, comment if something additional should be done.

**Comment by dakrone** [comment]
I have tried to build on Fedora 22 from the spec file, however, it doesn't actually build anything (after following the instructions in the README.md):

```
~/scratch/zeal-packaging/redhat:master λ rpmbuild --clean zeal.spec
Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.IlZ67D
+ umask 022
+ cd /home/hinmanm/rpmbuild/BUILD
+ rm -rf zeal-0.1.1
+ exit 0
```
