### ISSUE TITLE
Pre-Build Zeal Package for Debain

### ISSUE THREAD

**Issue by slashsBin** [zealdocs/zeal-packaging#11]
Hi incredible team of ZealDocs!
It would be so nice to have zeal available az pre-build package for Debian, specially for Debian Jessie.

Thanks!

**Comment by trollixx** [comment]
Currently Zeal only [available](https://packages.debian.org/search?suite=all&searchon=names&keywords=zeal) for testing and unstable. I'll look into options for other Debian releases.

**Comment by r3c4ll** [comment]
Great @trollixx, also for Debian Wheezy if it is possible. Thanks!

**Comment by simplycycling** [comment]
Another vote for Jessie, please!

**Comment by anarcat** [comment]
To backport this to jessie, the main obstacle would seem to be QT 5.5. It seems to me it would be fairly simple to do a clean backport of this, i'm available to help with this if people need that.

**Comment by anarcat** [comment]
Turns out a backport is trivial. I documented it in my request for a backport to the current debian maintainer: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820833

**Comment by trollixx** [comment]
@anarcat Thanks! Honestly, I didn't even think about backports (not a Debian user myself). If @czchen could add Zeal to backports, that would be pretty awesome, and resolve this issue.

Currently Zeal requires Qt 5.2+, which is quite old and should be available mostly everywhere. I'll keep this dependency unchanged for the upcoming Zeal 0.3. Then the plan is to switch to Qt 5.6 and drop support for unsupported Qt WebKit. I guess there won't be an easy way to support old distributions after that point.

**Comment by czchen** [comment]
@trollixx @anarcat I uploaded zeal to jessie-backports.

**Comment by trollixx** [comment]
@czchen Thank you!
