### ISSUE TITLE
Linux Mint

### ISSUE THREAD

**Issue by lsv** [zealdocs/zeal-packaging#12]
It would be nice if it was possible to get deb file for linux mint.

The problem is this

```
The following packages have unmet dependencies:
 zeal : Depends: libqt5x11extras5 (>= 5.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

```% sudo apt-get dist-upgrade``` gives me ```0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.```

**Comment by trollixx** [comment]
What deb-file are you trying to install?

**Comment by lsv** [comment]
That would be the one from ubuntu ppa
```ppa:zeal-developers/ppa```

My linux mint version is 17.1 (Rebecca) with Cinnamon.
Mint 17, is based on Ubuntu 14.04

**Comment by trollixx** [comment]
Closing this rather old issue. Zeal needs Qt 5.2+.
