### ISSUE TITLE
How to install in Ubuntu 12?

### ISSUE THREAD

**Issue by aschosser** [zealdocs/zeal-packaging#16]
I added your repository with "add-apt-repository ppa:zeal-developers/ppa". When I try "apt-get update" i get following error message:

http://ppa.launchpad.net/zeal-developers/ppa/ubuntu/dists/precise/main/source/Sources  404  Not Found

Can you please tell me, how to install zeal in Ubuntu 12?

Thank you,
Andreas

**Comment by trollixx** [comment]
Ubuntu 12.04 is way too old! It doesn't even have Qt 5, and Zeal requires at least Qt 5.2.  The only way would be to obtain all dependencies, and build Zeal yourself.

I think updating Ubuntu would be much easier, but I don't know your circumstances.
