### ISSUE TITLE
PPA doesn't work on Ubuntu 18.04 'bionic'

### ISSUE THREAD

**Issue by tokoiwesley** [zealdocs/zeal-packaging#39]
The repository 'http://ppa.launchpad.net/zeal-developers/ppa/ubuntu bionic Release' does not have a Release file.

**Comment by RoestVrijStaal** [comment]
Same here :sob: 

What's actually withholding the developer? Are some test data needed?

If creating a package per distro is too much hassle, the developer may consider to make an AppImage package instead...

**Comment by trollixx** [comment]
v0.6.1 has been uploaded to the PPA.
