### ISSUE TITLE
ppa buildings for xenial fail

### ISSUE THREAD

**Issue by Akronix** [zealdocs/zeal-packaging#40]
I'm using xenial with amd64 architecture and my last available version of zeal is 0.5.0.
In the ppa repo it says that build for 0.6.0 has failed: https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa/+build/14428541
And this is the build log: https://launchpadlibrarian.net/359786576/buildlog_ubuntu-xenial-amd64.zeal_1%3A0.6.0-1ppa1~xenial2_BUILDING.txt.gz

**Comment by trollixx** [comment]
@Epskampie could you also submit 0.6.1 for Xenial? It's the last version that will compile under 16.04.

**Comment by Epskampie** [comment]
I tried, but pbuilder for xenial was giving me grief. I’m using pbuilder to prevent more failed builds on the ppa since people keep commenting on them although they don’t do anything.

I’ll give it another try tonight.

**Comment by Epskampie** [comment]
After wrestling pbuilder for some minutes it is done. Would be good to turn off update checks by default for this version since there won't be a new one, I might do that in a patch later.

**Comment by Epskampie** [comment]
So, I did that as well. People on xenial who install from the ppa will have "update check"=false by default, as there won't be a new version for them.

**Comment by Akronix** [comment]
Awesome, hmm but wait, what do you mean by "there won't be a new one"?

**Comment by Epskampie** [comment]
Read above: trollix said that this is the last version that will compile on xenial. Upgrade yo distro if you want the newest zeal after this i guess. :-)

**Comment by trollixx** [comment]
Great, thank you @Epskampie!

@Akronix The next version of Zeal will not build against the Qt version shipped with 16.04. The policy is to support only the latest LTS release. Saying that, Flatpak, and soon Snap packages might work just fine since they provide own Qt libraries.

**Comment by Akronix** [comment]
got you. thanks for all your work :smiley: !
