### ISSUE TITLE
PPA doesn't work on Ubuntu 19.04 'disco'

### ISSUE THREAD

**Issue by DmitrySandalov** [zealdocs/zeal-packaging#45]
> The repository 'http://ppa.launchpad.net/zeal-developers/ppa/ubuntu disco Release' does not have a Release file.

**Comment by trollixx** [comment]
@Epskampie can you push an update for the new Ubuntu release? Thanks

**Comment by Epskampie** [comment]
I just added `0.6.1` builds for Ubuntu `disco` and `eoan`.

**Comment by Epskampie** [comment]
Although I think zeal is in the official repo's, so I don't really see the need :grin:

**Comment by trollixx** [comment]
Indeed, I always forget about the official repo. Thanks anyway!
