### ISSUE TITLE
Arch Linux package for Zeal seems to be missing

### ISSUE THREAD

**Issue by flaki** [zealdocs/zeal-packaging#46]
Did Zeal got removed from Arch's mainline distro? The download page lists `pacman -Syu zeal` as the preferred way to install Zeal on Arch Linux, but the package seems to be missing.

![image](https://user-images.githubusercontent.com/2089432/84022975-eecc3800-a98f-11ea-8cb0-1d3d72e5ccb8.png)

![image](https://user-images.githubusercontent.com/2089432/84023068-1b804f80-a990-11ea-97ce-84a267e9a6df.png)

**Comment by flaki** [comment]
Oh apparently `zeal` was [moved to AUR](https://aur.archlinux.org/packages/zeal/#comment-743388) recently:
![image](https://user-images.githubusercontent.com/2089432/84023304-83369a80-a990-11ea-98ed-9511b0066290.png)

So this seems like a documentation issue.

**Comment by gchamon** [comment]
![image](https://user-images.githubusercontent.com/9471861/191261629-fdb8b0ad-f841-499e-a73c-627d6fc1492f.png)
@flaki it seems correct now, this issue could be closed
