### ISSUE TITLE
Arch zeal and zeal-git packages do not list aarch64 as a supported platform. 

### ISSUE THREAD

**Issue by TkTech** [zealdocs/zeal-packaging#47]
Zeal builds and runs perfectly fine on Arch without modification for aarch64 (currently using it on a pinebook pro), but the PKGBUILD does not list aarch64 in its list of supported aarchs. Since trollixx is listed as the maintainer on the AUR package I'm posting here.

**Comment by trollixx** [comment]
Thanks for bringing this to my attention. I have updated `zeal-git. Commenting on AUR would've worked too!

I don't own `zeal` though, so you might need to leave a note on AUR about this.

**Comment by TkTech** [comment]
Thanks! Still new to the arch ecosystem!
