### ISSUE TITLE
Package request: Debian 11 "bullseye"

### ISSUE THREAD

**Issue by malaire** [zealdocs/zeal-packaging#48]

**Comment by cbednarski** [comment]
The Debian maintainer appears to be inactive https://tracker.debian.org/pkg/zeal

In the mean time an AppImage version would be helpful, since it doesn't depend on the distro, but the appimage effort seems to have stalled.

https://github.com/zealdocs/zeal/issues/1194

**Comment by trollixx** [comment]
Debian packages are handled upstream, nothing to do for us here.
