### ISSUE TITLE
Packaging for Fedora

### ISSUE THREAD

**Issue by meditans** [zealdocs/zeal-packaging#6]
What is the recommended way to install zeal on Fedora?

**Comment by trollixx** [comment]
I thought Fedora is RedHat compatible. Have you tried our [spec file](https://github.com/zealdocs/zeal-packaging/tree/master/redhat) for RedHat?

**Comment by meditans** [comment]
You're right, I missed that page, because I expected to see `fedora` and didn't occur to me to look for `redhat`. I installed zeal from source before opening the issue, however (and I love it :)

You may want to add the link to the spec file page to [the download page](https://zealdocs.org/download.html), just for additional clarity.

Thanks!
