### ISSUE TITLE
Ubuntu PPA has no v0.2.0 and Wily packages

### ISSUE THREAD

**Issue by atleta** [zealdocs/zeal-packaging#7]
Hi,

The ubuntu PPA seems to be abandoned: v0.2.0 is not published and the PPA doesn't contain a build for the current (15.10) distribution. After adding the PPA, aptitude can't fetch the package list:
W: Failed to fetch http://ppa.launchpad.net/zeal-developers/ppa/ubuntu/dists/wily/main/binary-amd64/Packages: 404  Not Found
W: Failed to fetch http://ppa.launchpad.net/zeal-developers/ppa/ubuntu/dists/wily/main/binary-i386/Packages: 404  Not Found

**Comment by henrjk** [comment]
I ran into this issue as well.

**Comment by trollixx** [comment]
Zeal 0.2.1 is available in PPA.

**Comment by henrjk** [comment]
works for me. Thank you!
